# Qdrant Collection Schema for Physical AI & Humanoid Robotics Book

collections:
  book_chunks:
    vectors:
      size: 1536  # For OpenAI text-embedding-3-small
      distance: Cosine
    payload_schema:
      doc_id:
        data_type: keyword
        field_type: keyword
      chunk_id:
        data_type: keyword
        field_type: keyword
      title:
        data_type: keyword
        field_type: keyword
      module:
        data_type: keyword
        field_type: keyword
      path:
        data_type: keyword
        field_type: keyword
      source_text:
        data_type: text
        field_type: text
      created_at:
        data_type: integer
        field_type: integer
      is_code_block:
        data_type: keyword
        field_type: keyword
      module_type:
        data_type: keyword
        field_type: keyword

# Collection configuration
collection_config:
  book_chunks:
    optimizers_config:
      deleted_threshold: 0.2
      vacuum_min_vector_number: 1000
      indexing_threshold: 20000
      flush_interval_sec: 10
      max_optimization_threads: 1